DROP SEQUENCE STATIONS_station_id_seq;
DROP SEQUENCE CTA_TRAINS_train_numb_seq;
DROP SEQUENCE TRAIN_SCHEDULE_sched_id_seq;
DROP SEQUENCE TRAIN_STOPS_stop_id_seq;
DROP SEQUENCE TRAIN_CONDUCTORS_cond_id_seq;
DROP SEQUENCE TRAIN_CONDUCTORS_sched_id_seq;
DROP SEQUENCE PASSENGERS_pass_id_seq;

CREATE SEQUENCE STATIONS_station_id_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 100
  NOCYCLE;
  
CREATE SEQUENCE CTA_TRAINS_train_numb_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 75
  NOCYCLE;
  
CREATE SEQUENCE TRAIN_SCHEDULE_sched_id_seq
  INCREMENT BY 1
  START WITH 00001
  MAXVALUE 99999
  CACHE 1500
  NOCYCLE;
  
CREATE SEQUENCE TRAIN_STOPS_stop_id_seq
  INCREMENT BY 1
  START WITH 00001
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE TRAIN_CONDUCTORS_cond_id_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 75
  NOCYCLE;

CREATE SEQUENCE TRAIN_CONDUCTORS_sched_id_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 75
  NOCYCLE;
  
CREATE SEQUENCE PASSENGERS_pass_id_seq
  INCREMENT BY 1
  START WITH 00001
  MAXVALUE 99999
  CACHE 5000
  NOCYCLE;