DROP SEQUENCE STATIONS_station_id_seq;
DROP SEQUENCE CTA_TRAINS_train_numb_seq;
DROP SEQUENCE TRAIN_SCHEDULE_sched_id_seq;
DROP SEQUENCE TRAIN_STOPS_stop_id_seq;
DROP SEQUENCE TRAIN_CONDUCTORS_cond_id_seq;
DROP SEQUENCE TRAIN_CONDUCTORS_sched_id_seq;
DROP SEQUENCE PASSENGERS_pass_id_seq;

CREATE SEQUENCE STATIONS_station_id_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 100
  NOCYCLE;
  
CREATE SEQUENCE CTA_TRAINS_train_numb_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 75
  NOCYCLE;
  
CREATE SEQUENCE TRAIN_SCHEDULE_sched_id_seq
  INCREMENT BY 1
  START WITH 00001
  MAXVALUE 99999
  CACHE 1500
  NOCYCLE;
  
CREATE SEQUENCE TRAIN_STOPS_stop_id_seq
  INCREMENT BY 1
  START WITH 00001
  MAXVALUE 99999
  NOCACHE
  NOCYCLE;
  
CREATE SEQUENCE TRAIN_CONDUCTORS_cond_id_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 75
  NOCYCLE;

CREATE SEQUENCE TRAIN_CONDUCTORS_sched_id_seq
  INCREMENT BY 1
  START WITH 001
  MAXVALUE 999
  CACHE 75
  NOCYCLE;
  
CREATE SEQUENCE PASSENGERS_pass_id_seq
  INCREMENT BY 1
  START WITH 00001
  MAXVALUE 99999
  CACHE 5000
  NOCYCLE;
  
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'O''Hare', 'O''Hare is a stop to dissembark passengers at the Chicago O''Hare International Airport', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Rosemont', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Cumberland', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Harlem (O''Hare Branch)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Jefferson Park', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Montrose', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Irving Park', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Addison (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Belmont (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Logan Square', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'California (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Western (O''Hare Branch', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Damen', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Division', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Chicago (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Grand (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Clark/Lake', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Washington', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Monroe (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Jackson', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'LaSalle', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Clinton (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'UIC-Halsted', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Racine', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Illinois Medical District', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Western (Forest Park Branch)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Kedzie-Homan', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Pulaski (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Cicero (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Austin (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Oak Park (Blue Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Harlem (Forest Park Branch)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Forest Park', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Harlem/Lake', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Oak Park (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Ridgeland', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Austin (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Central', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Laramie', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Cicero (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Pulaski (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Conservatory-Central Park Drive', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Kedzie', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'California (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Ashland', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Morgan', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Clinton (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'State/Lake', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Washington/Wabash', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Adams/Wabash', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Roosevelt', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Cermak-McCormick Place', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '35th-Bronzeville-IIT', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Indiana', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '43rd', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '47th (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '51st', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Garfield (Green Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Halsted', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Ashland/63rd', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Howard', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Jarvis', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Morse', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Loyola', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Granville', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Thorndale', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Bryn Mawr', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Berwyn', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Argyle', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Lawrence', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Wilson', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Sheridan', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Addison (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Belmont (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Fullerton', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'North/Clybourn', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Clark/Division', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Chicago (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Grand (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Lake', '', 'Y');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Monroe (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Harrison', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Cermak-Chinatown', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Sox-35th', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '47th (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Garfield (Red Line)', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '63rd', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '69th', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '79th', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '87th', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, '95th/Dan Ryan', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Dempster-Skokie', '', 'N');
INSERT INTO STATIONS VALUES
  (STATIONS_station_id_seq.NEXTVAL, 'Oakton-Skokie', '', 'N');
  
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (001, 'Blue Line', 'N');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (002, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (003, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (004, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (005, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (006, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (007, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (008, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (009, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (010, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (011, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (012, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (013, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (014, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (015, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (016, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (019, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (021, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (022, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (023, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (024, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (025, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (026, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (027, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (028, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (029, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (030, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (031, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (032, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (033, 'Blue Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (034, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (035, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (036, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (037, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (038, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (039, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (040, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (041, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (042, 'Green Line', 'N');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (043, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (044, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (045, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (046, 'Green Line', 'N');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (047, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (049, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (050, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (052, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (053, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (054, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (055, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (056, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (057, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (058, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (059, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (060, 'Green Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (062, 'Red Line', 'N');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (063, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (064, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (065, 'Red Line', 'N');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (066, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (067, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (068, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (069, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (070, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (071, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (072, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (073, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (074, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (075, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (076, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (077, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (078, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (079, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (081, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (082, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (083, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (084, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (085, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (086, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (087, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (088, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (089, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (090, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (091, 'Red Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (092, 'Yellow Line', 'Y');
INSERT INTO INDIVIDUAL_STATIONS VALUES
  (093, 'Yellow Line', 'Y');
  
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  bus_connection, loop_station) VALUES
  (017, 'Blue Line', 'Green Line', 'Y', 'Y');
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  bus_connection, loop_station) VALUES
  (018, 'Blue Line', 'Red Line', 'Y', 'Y');
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  bus_connection, loop_station) VALUES
  (019, 'Blue Line', 'Green Line', 'Y', 'Y');
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  bus_connection, loop_station) VALUES
  (048, 'Green Line', 'Red Line', 'Y', 'Y');
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  bus_connection, loop_station) VALUES
  (051, 'Green Line', 'Red Line', 'Y', 'Y');
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  bus_connection, loop_station) VALUES
  (061, 'Red Line', 'Yellow Line', 'Y', 'N');
INSERT INTO CONNECTING_STATIONS (station_id, connecting_line_1, connecting_line_2, 
  connecting_line_3, bus_connection, loop_station) VALUES
  (080, 'Red Line', 'Green Line', 'Blue Line', 'Y', 'Y');
  
INSERT INTO CTA_LINE VALUES
  ('BLU', 'Blue Line', 'The blue line transports passengers between O''Hare and Forest Park, including loop stops', 'O''Hare', 'Forest Park');
INSERT INTO CTA_LINE VALUES
  ('GRN', 'Green Line', 'The green line transports passengers between Harlem/Lake and Ashland/63rd, including loop stops', 'Harlem/Lake', 'Ashland/63rd');
INSERT INTO CTA_LINE VALUES
  ('RED', 'Red Line', 'The red line transports passengers between Howard and 95th/Dan Ryan, including loop stops', 'Howard', '95th/Dan Ryan');
INSERT INTO CTA_LINE VALUES
  ('YLW', 'Yellow Line', 'The yellow line transports passengers between Dempster-Skokie and Howard, does not go through loop stops', 'Dempster-Skokie', 'Howard');
  
INSERT INTO CTA_TRAINS VALUES
  ('BL001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL004', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL005', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL006', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL007', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL008', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL009', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL010', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL011', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL012', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL013', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL014', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL015', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('GR001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR004', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR005', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR006', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR007', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR008', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR009', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR010', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR011', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR012', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR013', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR014', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR015', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('RD001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD004', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD005', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD006', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD007', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD008', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD009', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD010', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD011', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD012', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD013', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD014', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD015', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('YL001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'YLW');
INSERT INTO CTA_TRAINS VALUES
  ('YL002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'YLW');
INSERT INTO CTA_TRAINS VALUES
  ('YL003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'YLW'); 

INSERT INTO CTA_TRACKS VALUES
  (001, 001);
INSERT INTO CTA_TRACKS VALUES
  (002, 002);
INSERT INTO CTA_TRACKS VALUES
  (003, 003);
INSERT INTO CTA_TRACKS VALUES
  (004, 004);
INSERT INTO CTA_TRACKS VALUES
  (005, 005);
INSERT INTO CTA_TRACKS VALUES
  (006, 006);
INSERT INTO CTA_TRACKS VALUES
  (007, 007);
INSERT INTO CTA_TRACKS VALUES
  (008, 008);

INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Brady', 'Tom', '12-DEC-00');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Allen', 'Josh', '24-APR-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Darnold', 'Sam', '12-DEC-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Fitzpatrick', 'Ryan', '09-MAR-19');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Luck', 'Andrew', '14-APR-12');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Foles', 'Nick', '01-JAN-19');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Mariota', 'Marcus', '26-AUG-15');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Watson', 'Deshaun', '15-SEP-17');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Mahomes', 'Patrick', '05-AUG-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Carr', 'Derek', '01-DEC-14');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Flacco', 'Joe', '02-FEB-19');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Rivers', 'Philip', '24-JUL-04');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Roethlisberger', 'Ben', '12-DEC-04');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Mayfield', 'Baker', '30-SEP-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Jackson', 'Lamar', '06-DEC-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Dalton', 'Andy', '02-FEB-13');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Trubisky', 'Mitchell', '19-OCT-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Rodgers', 'Aaron', '24-MAY-08');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Cousins', 'Kirk', '11-OCT-13');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Stafford', 'Matthew', '30-SEP-09');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Wilson', 'Russell', '30-AUG-11');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Rosen', 'Josh', '06-SEP-18');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Garropolo', 'Jimmy', '03-JUN-16');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Goff', 'Jared', '28-DEC-16');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Brees', 'Drew', '25-NOV-02');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Ryan', 'Matt', '13-OCT-08');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Newton', 'Cam', '01-APR-11');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Winston', 'Jameis', '29-APR-15');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Manning', 'Eli', '30-OCT-04');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Prescott', 'Dak', '12-SEP-17');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Keenum', 'Case', '09-APR-19');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Wentz', 'Carson', '12-MAY-16');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Cassel', 'Matt', '04-NOV-00');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Taylor', 'Tyrod', '16-APR-15');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Sanchez', 'Mark', '31-OCT-09');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Tannenhill', 'Ryan', '15-APR-12');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Manning', 'Peyton', '04-JUL-98');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Garrard', 'David', '11-JAN-05');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Young', 'Vince', '10-SEP-09');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Schaub', 'Matt', '29-NOV-11');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Smith', 'Alex', '18-JUL-16');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Russell', 'JaMarcus', '25-AUG-07');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Plummer', 'Jake', '25-FEB-05');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Volek', 'Billy', '01-JUN-06');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Stewart', 'Kordell', '23-MAR-02');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Manziel', 'Johnny', '25-SEP-15');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'McNair', 'Steve', '06-DEC-06');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Palmer', 'Carson', '16-JAN-05');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Cutler', 'Jay', '02-APR-09');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Favre', 'Brett', '29-APR-94');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Bridgewater', 'Teddy', '18-OCT-14');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Kitna', 'Jon', '11-DEC-07');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Hasselbeck', 'Matt', '02-MAR-05');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Warner', 'Kurt', '27-FEB-09');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Kaepernick', 'Colin', '18-APR-11');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Bradford', 'Sam', '10-JUN-08');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Brooks', 'Aaron', '04-FEB-03');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Vick', 'Michael', '02-AUG-04');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Delhomme', 'Jake', '18-JUL-06');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Garcia', 'Jeff', '07-MAR-02');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Hostetler', 'Steve', '15-DEC-99');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Romo', 'Tony', '11-NOV-07');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'Griffin III', 'Robert', '25-APR-12');
INSERT INTO TRAIN_CONDUCTORS VALUES
  (TRAIN_CONDUCTORS_cond_id_seq.NEXTVAL, 'McNabb', 'Donovan', '29-JAN-00');
  
INSERT INTO CONDUCTORS_SCHEDULE VALUES
  (TRAIN_CONDUCTORS_sched_id_seq.NEXTVAL, 1, 'BL001', '12:00', '00:00');
  
INSERT INTO PASSENGERS VALUES
  (PASSENGERS_pass_id_seq.NEXTVAL, 'Forsythe', 'Daniel', 001, 005, 'BL001', 001, 002);
INSERT INTO PASSENGERS VALUES
  (PASSENGERS_pass_id_seq.NEXTVAL, 'Basic', 'Ena', 001, 006, 'BL001', 001, 001);
  
INSERT INTO TRAIN_SCHEDULE VALUES
  (TRAIN_SCHEDULE_sched_id_seq.NEXTVAL, 'BL001', 001);  
  
INSERT INTO TRAIN_STOPS VALUES
  (TRAIN_STOPS_stop_id_seq.NEXTVAL, 1, '12:00', '12:00', 001, 00001, 'N', '16-APR-19');
INSERT INTO TRAIN_STOPS VALUES
  (TRAIN_STOPS_stop_id_seq.NEXTVAL, 2, '12:01', '12:02', 002, 00001, 'N', '16-APR-19');
INSERT INTO TRAIN_STOPS VALUES
  (TRAIN_STOPS_stop_id_seq.NEXTVAL, 3, '12:03', '12:04', 003, 00001, 'N', '16-APR-19');
INSERT INTO TRAIN_STOPS VALUES
  (TRAIN_STOPS_stop_id_seq.NEXTVAL, 4, '12:05', '12:06', 004, 00001, 'N', '16-APR-19');
INSERT INTO TRAIN_STOPS VALUES
  (TRAIN_STOPS_stop_id_seq.NEXTVAL, 5, '12:07', '12:08', 005, 00001, 'N', '16-APR-19');
INSERT INTO TRAIN_STOPS VALUES
  (TRAIN_STOPS_stop_id_seq.NEXTVAL, 6, '12:09', '12:10', 006, 00001, 'N', '16-APR-19');
  