INSERT INTO CTA_TRAINS VALUES
  ('BL001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL004', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL005', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL006', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL007', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL008', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL009', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL010', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL011', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL012', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL013', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL014', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('BL015', CTA_TRAINS_train_numb_seq.NEXTVAL, 'BLU');
INSERT INTO CTA_TRAINS VALUES
  ('GR001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR004', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR005', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR006', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR007', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR008', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR009', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR010', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR011', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR012', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR013', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR014', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('GR015', CTA_TRAINS_train_numb_seq.NEXTVAL, 'GRN');
INSERT INTO CTA_TRAINS VALUES
  ('RD001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD004', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD005', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD006', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD007', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD008', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD009', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD010', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD011', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD012', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD013', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD014', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('RD015', CTA_TRAINS_train_numb_seq.NEXTVAL, 'RED');
INSERT INTO CTA_TRAINS VALUES
  ('YL001', CTA_TRAINS_train_numb_seq.NEXTVAL, 'YLW');
INSERT INTO CTA_TRAINS VALUES
  ('YL002', CTA_TRAINS_train_numb_seq.NEXTVAL, 'YLW');
INSERT INTO CTA_TRAINS VALUES
  ('YL003', CTA_TRAINS_train_numb_seq.NEXTVAL, 'YLW');