SELECT * FROM STATIONS;
SELECT * FROM INDIVIDUAL_STATIONS;
SELECT * FROM CONNECTING_STATIONS;
SELECT * FROM CTA_LINE;
SELECT * FROM CTA_TRACKS;
SELECT * FROM CTA_TRAINS;
SELECT * FROM TRAIN_SCHEDULE;
SELECT * FROM TRAIN_STOPS;
SELECT * FROM TRAIN_CONDUCTORS;
SELECT * FROM CONDUCTORS_SCHEDULE;
SELECT * FROM PASSENGERS;

SELECT CTA_LINE.cta_id, CTA_LINE.line_name, 
  CTA_TRAINS.train_id,
  CONDUCTORS_SCHEDULE.schedule_id, CONDUCTORS_SCHEDULE.start_shift,
  TRAIN_CONDUCTORS.conductor_lname, TRAIN_CONDUCTORS.conductor_fname,
  TRAIN_SCHEDULE.train_schedule_id,
  CTA_TRACKS.track_number,
  TRAIN_STOPS.stop_id,
  PASSENGERS.pass_lname, PASSENGERS.pass_fname
FROM CTA_LINE
INNER JOIN CTA_TRAINS
ON CTA_LINE.cta_id = CTA_TRAINS.cta_id
INNER JOIN CONDUCTORS_SCHEDULE
ON CTA_TRAINS.train_id = CONDUCTORS_SCHEDULE.train_id
INNER JOIN TRAIN_CONDUCTORS
ON CONDUCTORS_SCHEDULE.conductor_id = TRAIN_CONDUCTORS.conductor_id
INNER JOIN TRAIN_SCHEDULE
ON CTA_TRAINS.train_id = TRAIN_SCHEDULE.train_id
INNER JOIN CTA_TRACKS
ON TRAIN_SCHEDULE.track_number = CTA_TRACKS.track_number
INNER JOIN TRAIN_STOPS
ON TRAIN_SCHEDULE.train_schedule_id = TRAIN_STOPS.train_schedule_id
INNER JOIN PASSENGERS
ON CTA_TRAINS.train_id = PASSENGERS.train_id;
